// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBssxcjADdEuRrz-De7UgzFnQ0uAR7ZVSY',
    appId: '1:206251759380:web:11f84aeb8bf5692993d401',
    messagingSenderId: '206251759380',
    projectId: 'focusx-ef63d',
    authDomain: 'focusx-ef63d.firebaseapp.com',
    storageBucket: 'focusx-ef63d.firebasestorage.app',
    measurementId: 'G-0703PEF52N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-XzrCyMeP5w2RNu-7guOgVQXqk_pmcs',
    appId: '1:206251759380:android:680bbd119258173c93d401',
    messagingSenderId: '206251759380',
    projectId: 'focusx-ef63d',
    storageBucket: 'focusx-ef63d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFA4m9APW7MAcpSWOgojEzvzvAh1SsqUg',
    appId: '1:206251759380:ios:6e8678edc67a702a93d401',
    messagingSenderId: '206251759380',
    projectId: 'focusx-ef63d',
    storageBucket: 'focusx-ef63d.firebasestorage.app',
    androidClientId: '206251759380-fv1nsuc51c3plqugejjt6g3k91rqisvj.apps.googleusercontent.com',
    iosClientId: '206251759380-2luo2ursnm7qps374274pnhhuqqq1tna.apps.googleusercontent.com',
    iosBundleId: 'com.vm.focusx',
  );
}
